# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jon Starnes - Blog, News and Resources for and by Open Data.
email: jstarne4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a place for my blog and portal to data science projects and portfolio pages
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jon-starnes.github.io" # the base hostname & protocol for your site
twitter_username: starj0n
github_username:  jon-starnes

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00aef3" #"#F70031"
  primary_rgb: "0,174,243" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#282d2e" # Now dark gray tint of primary - original #384452 "#33004D"
  link: "#0077a7" #
  link_hover: "#00da3e" #  variant of this lime green #00f345 original is #01b2fe
  footer_heading: "#9c9c9c" # white
  footer_content: "#8f8f8f" # light gray
